ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

exclude: ^LICENSE

repos:
  - repo: local
    hooks:
      - id: make_cmapnames
        name: make_cmapnames
        entry: python scripts/make_cmapnames.py --exit-code
        language: python
        files: src/cmap/data/[a-zA-Z0-9_]+/record.json
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format

  # commented out until PEP 639 is supported\
  # https://github.com/abravalheri/validate-pyproject/issues/70
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: "^src/"
        additional_dependencies:
          - numpy>=2.2
        stages:
          - pre-push
