#!/usr/bin/env python3
"""Generate a `Literal[...]` type annotation for named colormaps."""

import json
import sys
from argparse import ArgumentParser
from difflib import unified_diff
from pathlib import Path

scripts_dir = Path(__file__).resolve().parent
module_dir = scripts_dir.parent.joinpath("src", "cmap")
data_dir = module_dir.joinpath("data")
out_file = module_dir.joinpath("_colormapname.py")

SCRIPT_TEMPLATE = '''
"""Type annotation for literal colormap names.

Auto-generated by make_cmapnames.py : DO NOT EDIT.
"""
from typing import Literal, TypeAlias

ColormapName: TypeAlias = Literal[
{}]
'''.lstrip()


def generate_script():
    """Produce the expected script."""
    names = []

    for rel_path in sorted(data_dir.glob("*/record.json")):
        p = data_dir.joinpath(rel_path)
        prefix_name = rel_path.parent.name
        with p.open() as f:
            d = json.load(f)

        for subname in d.get("colormaps", []):
            for prefix in ["", f"{prefix_name}:"]:
                for suffix in ["", "_r"]:
                    names.append(f"{prefix}{subname.lower()}{suffix}")

    names_fmt = "".join(" " * 4 + f'"{n}",\n' for n in names)

    return SCRIPT_TEMPLATE.format(names_fmt)


def main(args=None):
    """Main function for this script."""
    parser = ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help=("do not write results, just print the diff and exit code 1 if non-empty"),
    )
    parser.add_argument(
        "--exit-code",
        action="store_true",
        help=("write the results, but return exit code 1 if there are changes to make"),
    )

    parsed = parser.parse_args(args)

    new = generate_script()
    old = out_file.read_text() if out_file.is_file() else ""

    if new == old:
        return 0

    if parsed.check:
        sys.stdout.writelines(
            unified_diff(
                old.splitlines(keepends=True),
                new.splitlines(keepends=True),
                fromfile="existing",
                tofile="new",
            )
        )
        return 1

    out_file.write_text(new)
    if parsed.exit_code:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
